[project]
name = "python-dsa-roadmap"
version = "0.1.0"
description = "A roadmap for learning data structures and algorithms in Python."
authors = [
    { name = "Khalil Saboor", email = "khalilsaboor1@gmail.com" }]
requires-python = ">=3.13"
dependencies = []
